### ISSUE TITLE
دسخوش

### ISSUE THREAD

**Issue by BlackIQ** [shabane/telegram_wrapper_api#1]
باو دمت گرم ستون.

**Comment by shabane** [comment]
> باو دمت گرم ستون.

چرا؟😂

**Comment by BlackIQ** [comment]
کفم برید با این حرکت سکسی که زدی.

من قرار بود بفرستم یادم نبود 😁

بعد لعنتی تو با این روتی که نوشتی همه چیز رو هندل میتونی کنی. دمت گرم.

**Comment by shabane** [comment]
در اصل من یه کانفیگ nginx نوشتم که proxy pass می‌کرد ولی چون پورت 443 سرورم مشغول بود و حتما باید 443 روی https می‌بود که پروکس پس درست انجام بشه، مجبور شدم اون کانفیگ رو دور بندازم :)))

**Comment by BlackIQ** [comment]
افرین.
